flutter_native_splash:
    color: "#000000"
name: base_flutter_framework
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  json_annotation:
  flutter_bloc: 7.0.0-nullsafety.5
  html_unescape: ^2.0.0
  flutter_linkify: 
  equatable: 
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #library UI
  cupertino_icons: 1.0.2 #icon
  page_transition: #view pager
  flutter_svg: 0.21.0-nullsafety.0 #get svg image
  awesome_dialog: 2.0.0-nullsafety.0 # dialog common
  flutter_native_splash: 1.1.4+1 #native background
  flutter_launcher_icons: 0.9.0 #icon
  cached_network_image: 3.0.0 #image network
  line_icons: 2.0.1 #icon
  pin_input_text_field: 4.0.0 #pin input text
  progress_indicators: 1.0.0
  rflutter_alert: 2.0.2 #dialog 
  liquid_pull_to_refresh: 3.0.0 #refresh view
  flutter_switch: 0.3.1 #select box
  implicitly_animated_reorderable_list: 0.4.0 #list
  pull_to_refresh: 2.0.0
  skeleton_text: 3.0.0
  no_context_navigation: 
  flutter_parsed_text: 2.2.1
  transparent_image: 2.0.0
  flutter_rating_bar: 4.0.0
  custom_radio_grouped_button: 2.1.1
  flutter_datetime_picker: 1.5.1
  flutter_colorpicker: 1.0.1
  
  

  #libary service
  dio: 4.0.1 #rest api
  sign_in_with_apple: 
  firebase_auth:  #authencation firebase
  flutter_facebook_auth: 3.5.2 #facebook authen
  firebase_core: 
  shared_preferences: 2.0.5 #cahce data
  firebase_messaging: 10.0.2 #noti firebase
  flutter_local_notifications: 5.0.0+1 #firebase noti
  firebase_crashlytics: 2.0.1 #firebase crash lytic
  firebase_dynamic_links: 
  http:
  giphy_picker: 2.0.0 #gif image
  http_parser: 4.0.0 #http format
  google_sign_in: 5.1.1
  flutter_chat_types: 
  file_picker: 4.1.4
  socket_io_client: 1.0.1
  sliding_up_panel: 2.0.0+1
  geocoding: 2.0.1
  geolocator: 7.7.1
  # flutter_socket_io: ^0.6.0
  # flutter_facebook_auth:  #facebook authen
  # firebase_auth:

  #library function
  share: 2.0.1 #share button
  images_picker: 1.2.4 #picker image 
  url_launcher: 
  page_indicator: 0.4.1 #page indicator

  clipboard: 0.1.3 # save cache text
  uni_links: 0.5.1 #deep link
  qr_code_scanner: 0.4.0 #qr scan
  image_downloader: 0.30.0 #down load image
  permission_handler: 8.0.0+2 # permission android
  location: 4.2.3 #get location
  flutter_native_image: 0.0.6 #down load and save image
  image_picker: 0.8.4+2
  group_button: ^3.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/launcher/
    - assets/fonts/
    - assets/images/
    - assets/images/logo.png
    - lib/utils/resource/resource_icon/  




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900
        - asset: assets/fonts/helvetica-neue-regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
